/**
 *
 * This file is autogenerated.
 *
 * DO NOT EDIT DIRECTLY
 *
 **/

import type { Bridge } from '../../bridge';

import type {
  ApiResponsePayload,
  BaseApiRequestMessage,
  BaseApiResponseMessage,
  BaseUrlParams,
} from '../../types';

export type CspmregistrationRequestApi = 'cspmregistration';

export type CommonApiResponseMessage =
  BaseApiResponseMessage<ApiResponsePayload>;

export interface CommonApiRequestMessage
  extends BaseApiRequestMessage<BaseUrlParams, unknown> {
  api: CspmregistrationRequestApi;
}

// types for postSettingsAccountsAggregatesCountsByStatusV1

export type PostSettingsAccountsAggregatesCountsByStatusV1QueryParams =
  BaseUrlParams;

export type PostSettingsAccountsAggregatesCountsByStatusV1ApiResponse =
  ApiResponsePayload;

export interface PostSettingsAccountsAggregatesCountsByStatusV1PostData {}

export type PostSettingsAccountsAggregatesCountsByStatusV1ResponseMessage =
  BaseApiResponseMessage<PostSettingsAccountsAggregatesCountsByStatusV1ApiResponse>;

export interface PostSettingsAccountsAggregatesCountsByStatusV1RequestMessage
  extends BaseApiRequestMessage<
    PostSettingsAccountsAggregatesCountsByStatusV1QueryParams,
    PostSettingsAccountsAggregatesCountsByStatusV1PostData
  > {
  api: CspmregistrationRequestApi;
  method: 'postSettingsAccountsAggregatesCountsByStatusV1';
}

// general types

export type CspmregistrationApiRequestMessage =
  PostSettingsAccountsAggregatesCountsByStatusV1RequestMessage;

export type CspmregistrationApiResponseMessage =
  PostSettingsAccountsAggregatesCountsByStatusV1ResponseMessage;

export class CspmregistrationApiBridge {
  private bridge;

  constructor(bridge: Bridge) {
    this.bridge = bridge;
  }

  getBridge() {
    return this.bridge;
  }

  async postSettingsAccountsAggregatesCountsByStatusV1(
    postBody: PostSettingsAccountsAggregatesCountsByStatusV1PostData,
    urlParams: PostSettingsAccountsAggregatesCountsByStatusV1QueryParams = {},
  ): Promise<PostSettingsAccountsAggregatesCountsByStatusV1ApiResponse> {
    const message: PostSettingsAccountsAggregatesCountsByStatusV1RequestMessage =
      {
        type: 'api',
        api: 'cspmregistration',
        method: 'postSettingsAccountsAggregatesCountsByStatusV1',
        payload: {
          body: postBody,
          params: urlParams,
        },
      };

    return this.bridge.postMessage(message);
  }
}
