/**
 *
 * This file is autogenerated.
 *
 * DO NOT EDIT DIRECTLY
 *
 **/

import type { Bridge } from '../../bridge';

import type {
  ApiResponsePayload,
  BaseApiRequestMessage,
  BaseApiResponseMessage,
  BaseUrlParams,
} from '../../types';

export type UserManagementRequestApi = 'userManagement';

export type CommonApiResponseMessage =
  BaseApiResponseMessage<ApiResponsePayload>;

export interface CommonApiRequestMessage
  extends BaseApiRequestMessage<BaseUrlParams, unknown> {
  api: UserManagementRequestApi;
}

// types for postEntitiesUsersGetV1

export type PostEntitiesUsersGetV1QueryParams = BaseUrlParams;

export type PostEntitiesUsersGetV1ApiResponse = ApiResponsePayload;

export interface PostEntitiesUsersGetV1PostData {}

export type PostEntitiesUsersGetV1ResponseMessage =
  BaseApiResponseMessage<PostEntitiesUsersGetV1ApiResponse>;

export interface PostEntitiesUsersGetV1RequestMessage
  extends BaseApiRequestMessage<
    PostEntitiesUsersGetV1QueryParams,
    PostEntitiesUsersGetV1PostData
  > {
  api: UserManagementRequestApi;
  method: 'postEntitiesUsersGetV1';
}

// general types

export type UserManagementApiRequestMessage =
  PostEntitiesUsersGetV1RequestMessage;

export type UserManagementApiResponseMessage =
  PostEntitiesUsersGetV1ResponseMessage;

export class UserManagementApiBridge {
  private bridge;

  constructor(bridge: Bridge) {
    this.bridge = bridge;
  }

  getBridge() {
    return this.bridge;
  }

  async postEntitiesUsersGetV1(
    postBody: PostEntitiesUsersGetV1PostData,
    urlParams: PostEntitiesUsersGetV1QueryParams = {},
  ): Promise<PostEntitiesUsersGetV1ApiResponse> {
    const message: PostEntitiesUsersGetV1RequestMessage = {
      type: 'api',
      api: 'userManagement',
      method: 'postEntitiesUsersGetV1',
      payload: {
        body: postBody,
        params: urlParams,
      },
    };

    return this.bridge.postMessage(message);
  }
}
