/**
 *
 * This file is autogenerated.
 *
 * DO NOT EDIT DIRECTLY
 *
 **/

import type { Bridge } from '../../bridge';

import type {
  ApiResponsePayload,
  BaseApiRequestMessage,
  BaseApiResponseMessage,
  BaseUrlParams,
  QueryParam,
} from '../../types';

export type FaasGatewayRequestApi = 'faasGateway';

export type CommonApiResponseMessage =
  BaseApiResponseMessage<ApiResponsePayload>;

export interface CommonApiRequestMessage
  extends BaseApiRequestMessage<BaseUrlParams, {}> {
  api: FaasGatewayRequestApi;
}

// types for getEntitiesExecutionV1

export interface GetEntitiesExecutionV1QueryParams extends BaseUrlParams {
  id: QueryParam;
}

export type GetEntitiesExecutionV1ApiResponse = ApiResponsePayload;

export type GetEntitiesExecutionV1ResponseMessage =
  BaseApiResponseMessage<GetEntitiesExecutionV1ApiResponse>;

export interface GetEntitiesExecutionV1RequestMessage
  extends BaseApiRequestMessage<GetEntitiesExecutionV1QueryParams> {
  api: FaasGatewayRequestApi;
  method: 'getEntitiesExecutionV1';
}

// types for postEntitiesExecutionV1

export type PostEntitiesExecutionV1QueryParams = BaseUrlParams;

export type PostEntitiesExecutionV1ApiResponse = ApiResponsePayload;

export interface PostEntitiesExecutionV1PostData {}

export type PostEntitiesExecutionV1ResponseMessage =
  BaseApiResponseMessage<PostEntitiesExecutionV1ApiResponse>;

export interface PostEntitiesExecutionV1RequestMessage
  extends BaseApiRequestMessage<
    PostEntitiesExecutionV1QueryParams,
    PostEntitiesExecutionV1PostData
  > {
  api: FaasGatewayRequestApi;
  method: 'postEntitiesExecutionV1';
}

// general types

export type FaasGatewayApiRequestMessage =
  | GetEntitiesExecutionV1RequestMessage
  | PostEntitiesExecutionV1RequestMessage;

export type FaasGatewayApiResponseMessage =
  | GetEntitiesExecutionV1ResponseMessage
  | PostEntitiesExecutionV1ResponseMessage;

export class FaasGatewayApiBridge {
  private bridge;

  constructor(bridge: Bridge) {
    this.bridge = bridge;
  }

  getBridge() {
    return this.bridge;
  }

  async getEntitiesExecutionV1(
    urlParams: GetEntitiesExecutionV1QueryParams
  ): Promise<GetEntitiesExecutionV1ApiResponse> {
    const message: GetEntitiesExecutionV1RequestMessage = {
      type: 'api',
      api: 'faasGateway',
      method: 'getEntitiesExecutionV1',
      payload: {
        params: urlParams,
      },
    };

    return this.bridge.postMessage(message);
  }

  async postEntitiesExecutionV1(
    postBody: PostEntitiesExecutionV1PostData,
    urlParams: PostEntitiesExecutionV1QueryParams = {}
  ): Promise<PostEntitiesExecutionV1ApiResponse> {
    const message: PostEntitiesExecutionV1RequestMessage = {
      type: 'api',
      api: 'faasGateway',
      method: 'postEntitiesExecutionV1',
      payload: {
        body: postBody,
        params: urlParams,
      },
    };

    return this.bridge.postMessage(message);
  }
}
