/**
*
* This file is autogenerated from the configuration file at `config/apis/remote-response.json`.
*
* DO NOT EDIT DIRECTLY
*
* If you need to change the contents of this file please edit the above configuration file and
* then run:
*
* ```
* yarn cs-gen platform-apis
* ```
*
**/

import type {
GetQueriesScriptsV1QueryParams,
  PostEntitiesScriptsGetV2QueryParams,
GetQueriesScriptsV1ApiResponse,
  PostEntitiesScriptsGetV2ApiResponse,
GetQueriesScriptsV1RequestMessage,
  PostEntitiesScriptsGetV2RequestMessage,
PostEntitiesScriptsGetV2PostData,
} from './types';

import type { Bridge } from '../../bridge';

export class RemoteResponseApiBridge {

private bridge;

constructor(bridge: Bridge) {
  this.bridge = bridge;
}


    async getScriptIds(urlParams: GetQueriesScriptsV1QueryParams = {}): Promise<GetQueriesScriptsV1ApiResponse> {
        
            const message: GetQueriesScriptsV1RequestMessage = {
                type: 'api',
                api: 'remoteResponse',
                method: 'getQueriesScriptsV1',
                payload: {
                  params: urlParams,
                },
            };
        

        return this.bridge.postMessage(message);
    }

    async getScriptEntities(postBody: PostEntitiesScriptsGetV2PostData, urlParams: PostEntitiesScriptsGetV2QueryParams = {}): Promise<PostEntitiesScriptsGetV2ApiResponse> {
        
            const message: PostEntitiesScriptsGetV2RequestMessage = {
                type: 'api',
                api: 'remoteResponse',
                method: 'postEntitiesScriptsGetV2',
                payload: {
                  body: postBody,
                  params: urlParams,
                },
            };
        

        return this.bridge.postMessage(message);
    }

}
