/**
 *
 * This file is autogenerated from the configuration file at `config/apis/remote-response.json`.
 *
 * DO NOT EDIT DIRECTLY
 *
 * If you need to change the contents of this file please edit the above configuration file and
 * then run:
 *
 * ```
 * yarn cs-gen platform-apis
 * ```
 *
 **/

import type { BaseUrlParams, QueryParam } from '../types';

export interface GetQueriesScriptsV1QueryParams extends BaseUrlParams {
  filter?: string;
  limit?: QueryParam;
  offset?: QueryParam;
  sort?: QueryParam;
}

export interface PostEntitiesScriptsGetV2QueryParams extends BaseUrlParams {}
