/**
 *
 * This file is autogenerated from the configuration file at `config/apis/remote-response.json`.
 *
 * DO NOT EDIT DIRECTLY
 *
 * If you need to change the contents of this file please edit the above configuration file and
 * then run:
 *
 * ```
 * yarn cs-gen platform-apis
 * ```
 *
 **/

import type {
  BaseApiRequestMessage,
  BaseApiResponseMessage,
  ApiResponsePayload,
  BaseUrlParams,
  QueryParam,
} from '../../types';

export type RemoteResponseRequestApi = 'remoteResponse';

// types for getQueriesScriptsV1

export interface GetQueriesScriptsV1QueryParams extends BaseUrlParams {
  filter?: string;
  limit?: QueryParam;
  offset?: QueryParam;
  sort?: QueryParam;
}

export type GetQueriesScriptsV1ApiResponse = ApiResponsePayload<string>;

export interface GetQueriesScriptsV1RequestMessage
  extends BaseApiRequestMessage<GetQueriesScriptsV1QueryParams> {
  api: RemoteResponseRequestApi;
  method: 'getQueriesScriptsV1';
}

export type GetQueriesScriptsV1ResponseMessage =
  BaseApiResponseMessage<GetQueriesScriptsV1ApiResponse>;

// types for postEntitiesScriptsGetV2

export interface PostEntitiesScriptsGetV2QueryParams extends BaseUrlParams {}

export interface PostEntitiesScriptsGetV2PostData {}

export type PostEntitiesScriptsGetV2ApiResponse = ApiResponsePayload<any>;

export interface PostEntitiesScriptsGetV2RequestMessage
  extends BaseApiRequestMessage<
    PostEntitiesScriptsGetV2QueryParams,
    PostEntitiesScriptsGetV2PostData
  > {
  api: RemoteResponseRequestApi;
  method: 'postEntitiesScriptsGetV2';
}

export type PostEntitiesScriptsGetV2ResponseMessage =
  BaseApiResponseMessage<PostEntitiesScriptsGetV2ApiResponse>;

// general types

export type RemoteResponseApiRequestMessage =
  | GetQueriesScriptsV1RequestMessage
  | PostEntitiesScriptsGetV2RequestMessage;
export type RemoteResponseApiResponseMessage =
  | GetQueriesScriptsV1ResponseMessage
  | PostEntitiesScriptsGetV2ResponseMessage;
