/**
 *
 * This file is autogenerated.
 *
 * DO NOT EDIT DIRECTLY
 *
 **/

import type { Bridge } from '../../bridge';

import type {
  ApiResponsePayload,
  BaseApiRequestMessage,
  BaseApiResponseMessage,
  BaseUrlParams,
  QueryParam,
} from '../../types';

export type CspmRegistrationRequestApi = 'cspmRegistration';

export type CommonApiResponseMessage =
  BaseApiResponseMessage<ApiResponsePayload>;

export interface CommonApiRequestMessage
  extends BaseApiRequestMessage<BaseUrlParams, unknown> {
  api: CspmRegistrationRequestApi;
}

// types for getCspmregistrationCloudConnectCspmAzureCombinedAccountsV1

export interface GetCspmregistrationCloudConnectCspmAzureCombinedAccountsV1QueryParams
  extends BaseUrlParams {
  filter?: string;
  sort?: QueryParam;
  nextToken?: QueryParam;
  limit?: QueryParam;
  offset?: QueryParam;
}

export type GetCspmregistrationCloudConnectCspmAzureCombinedAccountsV1ApiResponse =
  ApiResponsePayload;

export type GetCspmregistrationCloudConnectCspmAzureCombinedAccountsV1ResponseMessage =
  BaseApiResponseMessage<GetCspmregistrationCloudConnectCspmAzureCombinedAccountsV1ApiResponse>;

export interface GetCspmregistrationCloudConnectCspmAzureCombinedAccountsV1RequestMessage
  extends BaseApiRequestMessage<GetCspmregistrationCloudConnectCspmAzureCombinedAccountsV1QueryParams> {
  api: CspmRegistrationRequestApi;
  method: 'getCspmregistrationCloudConnectCspmAzureCombinedAccountsV1';
}

// types for getCspmregistrationCloudConnectCspmGcpCombinedAccountsV1

export interface GetCspmregistrationCloudConnectCspmGcpCombinedAccountsV1QueryParams
  extends BaseUrlParams {
  filter?: string;
  sort?: QueryParam;
  nextToken?: QueryParam;
  limit?: QueryParam;
  offset?: QueryParam;
}

export type GetCspmregistrationCloudConnectCspmGcpCombinedAccountsV1ApiResponse =
  ApiResponsePayload;

export type GetCspmregistrationCloudConnectCspmGcpCombinedAccountsV1ResponseMessage =
  BaseApiResponseMessage<GetCspmregistrationCloudConnectCspmGcpCombinedAccountsV1ApiResponse>;

export interface GetCspmregistrationCloudConnectCspmGcpCombinedAccountsV1RequestMessage
  extends BaseApiRequestMessage<GetCspmregistrationCloudConnectCspmGcpCombinedAccountsV1QueryParams> {
  api: CspmRegistrationRequestApi;
  method: 'getCspmregistrationCloudConnectCspmGcpCombinedAccountsV1';
}

// general types

export type CspmRegistrationApiRequestMessage =
  | GetCspmregistrationCloudConnectCspmAzureCombinedAccountsV1RequestMessage
  | GetCspmregistrationCloudConnectCspmGcpCombinedAccountsV1RequestMessage;

export type CspmRegistrationApiResponseMessage =
  | GetCspmregistrationCloudConnectCspmAzureCombinedAccountsV1ResponseMessage
  | GetCspmregistrationCloudConnectCspmGcpCombinedAccountsV1ResponseMessage;

export class CspmRegistrationApiBridge {
  private bridge;

  constructor(bridge: Bridge) {
    this.bridge = bridge;
  }

  getBridge() {
    return this.bridge;
  }

  async getCspmregistrationCloudConnectCspmAzureCombinedAccountsV1(
    urlParams: GetCspmregistrationCloudConnectCspmAzureCombinedAccountsV1QueryParams = {},
  ): Promise<GetCspmregistrationCloudConnectCspmAzureCombinedAccountsV1ApiResponse> {
    const message: GetCspmregistrationCloudConnectCspmAzureCombinedAccountsV1RequestMessage =
      {
        type: 'api',
        api: 'cspmRegistration',
        method: 'getCspmregistrationCloudConnectCspmAzureCombinedAccountsV1',
        payload: {
          params: urlParams,
        },
      };

    return this.bridge.postMessage(message);
  }

  async getCspmregistrationCloudConnectCspmGcpCombinedAccountsV1(
    urlParams: GetCspmregistrationCloudConnectCspmGcpCombinedAccountsV1QueryParams = {},
  ): Promise<GetCspmregistrationCloudConnectCspmGcpCombinedAccountsV1ApiResponse> {
    const message: GetCspmregistrationCloudConnectCspmGcpCombinedAccountsV1RequestMessage =
      {
        type: 'api',
        api: 'cspmRegistration',
        method: 'getCspmregistrationCloudConnectCspmGcpCombinedAccountsV1',
        payload: {
          params: urlParams,
        },
      };

    return this.bridge.postMessage(message);
  }
}
