/**
 *
 * This file is autogenerated.
 *
 * DO NOT EDIT DIRECTLY
 *
 **/

import type { Bridge } from '../../bridge';

import type {
  ApiResponsePayload,
  BaseApiRequestMessage,
  BaseApiResponseMessage,
  BaseUrlParams,
  QueryParam,
} from '../../types';

export type CloudregistrationRequestApi = 'cloudregistration';

export type CommonApiResponseMessage =
  BaseApiResponseMessage<ApiResponsePayload>;

export interface CommonApiRequestMessage
  extends BaseApiRequestMessage<BaseUrlParams, unknown> {
  api: CloudregistrationRequestApi;
}

// types for getCloudSecurityRegistrationAwsCombinedAccountsV1

export interface GetCloudSecurityRegistrationAwsCombinedAccountsV1QueryParams
  extends BaseUrlParams {
  filter?: string;
  sort?: QueryParam;
  nextToken?: QueryParam;
  limit?: QueryParam;
  offset?: QueryParam;
  ids?: QueryParam;
  organizationIds?: QueryParam;
  status?: QueryParam;
  updateUrls?: QueryParam;
}

export type GetCloudSecurityRegistrationAwsCombinedAccountsV1ApiResponse =
  ApiResponsePayload;

export type GetCloudSecurityRegistrationAwsCombinedAccountsV1ResponseMessage =
  BaseApiResponseMessage<GetCloudSecurityRegistrationAwsCombinedAccountsV1ApiResponse>;

export interface GetCloudSecurityRegistrationAwsCombinedAccountsV1RequestMessage
  extends BaseApiRequestMessage<GetCloudSecurityRegistrationAwsCombinedAccountsV1QueryParams> {
  api: CloudregistrationRequestApi;
  method: 'getCloudSecurityRegistrationAwsCombinedAccountsV1';
}

// general types

export type CloudregistrationApiRequestMessage =
  GetCloudSecurityRegistrationAwsCombinedAccountsV1RequestMessage;

export type CloudregistrationApiResponseMessage =
  GetCloudSecurityRegistrationAwsCombinedAccountsV1ResponseMessage;

export class CloudregistrationApiBridge {
  private bridge;

  constructor(bridge: Bridge) {
    this.bridge = bridge;
  }

  getBridge() {
    return this.bridge;
  }

  async getCloudSecurityRegistrationAwsCombinedAccountsV1(
    urlParams: GetCloudSecurityRegistrationAwsCombinedAccountsV1QueryParams = {},
  ): Promise<GetCloudSecurityRegistrationAwsCombinedAccountsV1ApiResponse> {
    const message: GetCloudSecurityRegistrationAwsCombinedAccountsV1RequestMessage =
      {
        type: 'api',
        api: 'cloudregistration',
        method: 'getCloudSecurityRegistrationAwsCombinedAccountsV1',
        payload: {
          params: urlParams,
        },
      };

    return this.bridge.postMessage(message);
  }
}
