/**
 *
 * This file is autogenerated.
 *
 * DO NOT EDIT DIRECTLY
 *
 **/

import type { Bridge } from '../../bridge';

import type {
  ApiResponsePayload,
  BaseApiRequestMessage,
  BaseApiResponseMessage,
  BaseUrlParams,
  QueryParam,
} from '../../types';

export type MitreRequestApi = 'mitre';

export type CommonApiResponseMessage =
  BaseApiResponseMessage<ApiResponsePayload>;

export interface CommonApiRequestMessage
  extends BaseApiRequestMessage<BaseUrlParams, unknown> {
  api: MitreRequestApi;
}

// types for getIntelMitreEntitiesMatrixV1

export interface GetIntelMitreEntitiesMatrixV1QueryParams
  extends BaseUrlParams {
  version?: QueryParam;
}

export type GetIntelMitreEntitiesMatrixV1ApiResponse = ApiResponsePayload;

export type GetIntelMitreEntitiesMatrixV1ResponseMessage =
  BaseApiResponseMessage<GetIntelMitreEntitiesMatrixV1ApiResponse>;

export interface GetIntelMitreEntitiesMatrixV1RequestMessage
  extends BaseApiRequestMessage<GetIntelMitreEntitiesMatrixV1QueryParams> {
  api: MitreRequestApi;
  method: 'getIntelMitreEntitiesMatrixV1';
}

// general types

export type MitreApiRequestMessage =
  GetIntelMitreEntitiesMatrixV1RequestMessage;

export type MitreApiResponseMessage =
  GetIntelMitreEntitiesMatrixV1ResponseMessage;

export class MitreApiBridge {
  private bridge;

  constructor(bridge: Bridge) {
    this.bridge = bridge;
  }

  getBridge() {
    return this.bridge;
  }

  async getIntelMitreEntitiesMatrixV1(
    urlParams: GetIntelMitreEntitiesMatrixV1QueryParams = {},
  ): Promise<GetIntelMitreEntitiesMatrixV1ApiResponse> {
    const message: GetIntelMitreEntitiesMatrixV1RequestMessage = {
      type: 'api',
      api: 'mitre',
      method: 'getIntelMitreEntitiesMatrixV1',
      payload: {
        params: urlParams,
      },
    };

    return this.bridge.postMessage(message);
  }
}
