/**
 *
 * This file is autogenerated from the available APIs for App Platform.
 *
 * DO NOT EDIT DIRECTLY
 *
 * If you need to change the contents of this file please edit the above configuration file and
 * then run:
 *
 * ```
 * yarn cs-gen platform-apis
 * ```
 *
 **/

export type ApiIdentifier = 'incidents' | 'remoteResponse';
