/**
 *
 * This file is autogenerated.
 *
 * DO NOT EDIT DIRECTLY
 *
 **/

export type ApiIdentifier =
  | 'actors'
  | 'alerts'
  | 'detects'
  | 'devices'
  | 'fwmgr'
  | 'incidents'
  | 'mitre'
  | 'plugins'
  | 'remoteResponse'
  | 'userManagement'
  | 'workflows'
  | 'customobjects'
  | 'faasGateway'
  | 'loggingapi';
