/**
 *
 * This file is autogenerated.
 *
 * DO NOT EDIT DIRECTLY
 *
 **/

export type ApiIdentifier =
  | 'alerts'
  | 'detects'
  | 'devices'
  | 'fwmgr'
  | 'incidents'
  | 'mitre'
  | 'plugins'
  | 'remoteResponse'
  | 'userManagement'
  | 'workflows'
  | 'cloudSecurityAssets'
  | 'cloudregistration'
  | 'containerSecurity'
  | 'cspmRegistration'
  | 'cspmregistration'
  | 'customobjects'
  | 'faasGateway'
  | 'loggingapi'
  | 'registryAssessment';
