/**
 *
 * This file is autogenerated.
 *
 * DO NOT EDIT DIRECTLY
 *
 **/

import { Memoize } from 'typescript-memoize';

import { AlertsApiBridge } from './alerts';
import { CustomobjectsApiBridge } from './customobjects';
import { DetectsApiBridge } from './detects';
import { DevicesApiBridge } from './devices';
import { FaasGatewayApiBridge } from './faas-gateway';
import { FwmgrApiBridge } from './fwmgr';
import { IncidentsApiBridge } from './incidents';
import { LoggingapiApiBridge } from './loggingapi';
import { MitreApiBridge } from './mitre';
import { PluginsApiBridge } from './plugins';
import { RemoteResponseApiBridge } from './remote-response';
import { UserManagementApiBridge } from './user-management';
import { WorkflowsApiBridge } from './workflows';

import { assertConnection } from '../utils';

import type FalconApi from '../api';

export default class FalconPublicApis {
  constructor(private api: FalconApi<any>) {}

  @Memoize()
  get alerts(): AlertsApiBridge {
    assertConnection(this.api);

    return new AlertsApiBridge(this.api.bridge);
  }

  @Memoize()
  get detects(): DetectsApiBridge {
    assertConnection(this.api);

    return new DetectsApiBridge(this.api.bridge);
  }

  @Memoize()
  get devices(): DevicesApiBridge {
    assertConnection(this.api);

    return new DevicesApiBridge(this.api.bridge);
  }

  @Memoize()
  get fwmgr(): FwmgrApiBridge {
    assertConnection(this.api);

    return new FwmgrApiBridge(this.api.bridge);
  }

  @Memoize()
  get incidents(): IncidentsApiBridge {
    assertConnection(this.api);

    return new IncidentsApiBridge(this.api.bridge);
  }

  @Memoize()
  get mitre(): MitreApiBridge {
    assertConnection(this.api);

    return new MitreApiBridge(this.api.bridge);
  }

  /**
   * @internal
   */
  @Memoize()
  get plugins(): PluginsApiBridge {
    assertConnection(this.api);

    return new PluginsApiBridge(this.api.bridge);
  }

  @Memoize()
  get remoteResponse(): RemoteResponseApiBridge {
    assertConnection(this.api);

    return new RemoteResponseApiBridge(this.api.bridge);
  }

  @Memoize()
  get userManagement(): UserManagementApiBridge {
    assertConnection(this.api);

    return new UserManagementApiBridge(this.api.bridge);
  }

  @Memoize()
  get workflows(): WorkflowsApiBridge {
    assertConnection(this.api);

    return new WorkflowsApiBridge(this.api.bridge);
  }

  /**
   * @internal
   */
  @Memoize()
  get customobjects(): CustomobjectsApiBridge {
    assertConnection(this.api);

    return new CustomobjectsApiBridge(this.api.bridge);
  }

  /**
   * @internal
   */
  @Memoize()
  get faasGateway(): FaasGatewayApiBridge {
    assertConnection(this.api);

    return new FaasGatewayApiBridge(this.api.bridge);
  }

  /**
   * @internal
   */
  @Memoize()
  get loggingapi(): LoggingapiApiBridge {
    assertConnection(this.api);

    return new LoggingapiApiBridge(this.api.bridge);
  }
}
