/**
 *
 * This file is autogenerated from the available APIs for App Platform.
 *
 * DO NOT EDIT DIRECTLY
 *
 * If you need to change the contents of this file please edit the above configuration file and
 * then run:
 *
 * ```
 * yarn cs-gen platform-apis
 * ```
 *
 **/

import {
  ConnectRequestMessage,
  LocalData,
  ConnectResponseMessage,
} from '../types';

import { RequestMessage } from './types';


    import {
    
    GetEntitiesActorsGetV2RequestMessage as Request00,
    GetEntitiesActorsGetV2ResponseMessage as Response00,
    GetQueriesActorsV2RequestMessage as Request01,
    GetQueriesActorsV2ResponseMessage as Response01,
    PostAggregatesActorsGetV2RequestMessage as Request02,
    PostAggregatesActorsGetV2ResponseMessage as Response02,
    PostEntitiesActorsGetV2RequestMessage as Request03,
    PostEntitiesActorsGetV2ResponseMessage as Response03,
    PostEntitiesMitreV1RequestMessage as Request04,
    PostEntitiesMitreV1ResponseMessage as Response04,
    } from './actors/types';

    import {
    
    DeleteEntitiesSuppressedDevicesV1RequestMessage as Request10,
    DeleteEntitiesSuppressedDevicesV1ResponseMessage as Response10,
    GetQueriesAlertsV1RequestMessage as Request11,
    GetQueriesAlertsV1ResponseMessage as Response11,
    PatchCombinedAlertsV2RequestMessage as Request12,
    PatchCombinedAlertsV2ResponseMessage as Response12,
    PatchEntitiesAlertsV2RequestMessage as Request13,
    PatchEntitiesAlertsV2ResponseMessage as Response13,
    PatchEntitiesSuppressedDevicesV1RequestMessage as Request14,
    PatchEntitiesSuppressedDevicesV1ResponseMessage as Response14,
    PostAggregatesAlertsV1RequestMessage as Request15,
    PostAggregatesAlertsV1ResponseMessage as Response15,
    PostEntitiesAlertsV1RequestMessage as Request16,
    PostEntitiesAlertsV1ResponseMessage as Response16,
    PostEntitiesSuppressedDevicesV1RequestMessage as Request17,
    PostEntitiesSuppressedDevicesV1ResponseMessage as Response17,
    } from './alerts/types';

    import {
    
    GetEntitiesSuppressedDevicesV1RequestMessage as Request20,
    GetEntitiesSuppressedDevicesV1ResponseMessage as Response20,
    PatchEntitiesDetectsV2RequestMessage as Request21,
    PatchEntitiesDetectsV2ResponseMessage as Response21,
    PatchQueriesDetectsV1RequestMessage as Request22,
    PatchQueriesDetectsV1ResponseMessage as Response22,
    PatchQueriesDetectsV2RequestMessage as Request23,
    PatchQueriesDetectsV2ResponseMessage as Response23,
    PostAggregatesDetectsGetV1RequestMessage as Request24,
    PostAggregatesDetectsGetV1ResponseMessage as Response24,
    PostEntitiesSummariesGetV1RequestMessage as Request25,
    PostEntitiesSummariesGetV1ResponseMessage as Response25,
    PostEntitiesSuppressedDevicesV1RequestMessage as Request26,
    PostEntitiesSuppressedDevicesV1ResponseMessage as Response26,
    } from './detects/types';

    import {
    
    DeleteEntitiesGroupsV1RequestMessage as Request30,
    DeleteEntitiesGroupsV1ResponseMessage as Response30,
    GetAggregatesBucketsV1RequestMessage as Request31,
    GetAggregatesBucketsV1ResponseMessage as Response31,
    GetAggregatesTagPrefixCountsV1RequestMessage as Request32,
    GetAggregatesTagPrefixCountsV1ResponseMessage as Response32,
    GetEntitiesGroupsV1RequestMessage as Request33,
    GetEntitiesGroupsV1ResponseMessage as Response33,
    GetEntitiesReleasesV1RequestMessage as Request34,
    GetEntitiesReleasesV1ResponseMessage as Response34,
    GetEntitiesRespondV1RequestMessage as Request35,
    GetEntitiesRespondV1ResponseMessage as Response35,
    GetQueriesAvailableGroupsV1RequestMessage as Request36,
    GetQueriesAvailableGroupsV1ResponseMessage as Response36,
    GetQueriesDevicesHiddenV2RequestMessage as Request37,
    GetQueriesDevicesHiddenV2ResponseMessage as Response37,
    GetQueriesDevicesV2RequestMessage as Request38,
    GetQueriesDevicesV2ResponseMessage as Response38,
    GetQueriesGroupsV1RequestMessage as Request39,
    GetQueriesGroupsV1ResponseMessage as Response39,
    PatchEntitiesDevicesTagsV2RequestMessage as Request310,
    PatchEntitiesDevicesTagsV2ResponseMessage as Response310,
    PatchEntitiesGroupsV1RequestMessage as Request311,
    PatchEntitiesGroupsV1ResponseMessage as Response311,
    PostAggregatesDevicesGetV1RequestMessage as Request312,
    PostAggregatesDevicesGetV1ResponseMessage as Response312,
    PostCombinedDevicesLoginHistoryV1RequestMessage as Request313,
    PostCombinedDevicesLoginHistoryV1ResponseMessage as Response313,
    PostEntitiesDevicesActionsV4RequestMessage as Request314,
    PostEntitiesDevicesActionsV4ResponseMessage as Response314,
    PostEntitiesDevicesHiddenActionsV4RequestMessage as Request315,
    PostEntitiesDevicesHiddenActionsV4ResponseMessage as Response315,
    PostEntitiesDevicesReportsV1RequestMessage as Request316,
    PostEntitiesDevicesReportsV1ResponseMessage as Response316,
    PostEntitiesDevicesV2RequestMessage as Request317,
    PostEntitiesDevicesV2ResponseMessage as Response317,
    PostEntitiesGroupActionsV1RequestMessage as Request318,
    PostEntitiesGroupActionsV1ResponseMessage as Response318,
    PostEntitiesGroupsV1RequestMessage as Request319,
    PostEntitiesGroupsV1ResponseMessage as Response319,
    PostEntitiesReleasesV1RequestMessage as Request320,
    PostEntitiesReleasesV1ResponseMessage as Response320,
    } from './devices/types';

    import {
    
    DeleteEntitiesNetworkLocationsV1RequestMessage as Request40,
    DeleteEntitiesNetworkLocationsV1ResponseMessage as Response40,
    DeleteEntitiesPoliciesV1RequestMessage as Request41,
    DeleteEntitiesPoliciesV1ResponseMessage as Response41,
    DeleteEntitiesRuleGroupsV1RequestMessage as Request42,
    DeleteEntitiesRuleGroupsV1ResponseMessage as Response42,
    GetEntitiesEventsV1RequestMessage as Request43,
    GetEntitiesEventsV1ResponseMessage as Response43,
    GetEntitiesFirewallFieldsV1RequestMessage as Request44,
    GetEntitiesFirewallFieldsV1ResponseMessage as Response44,
    GetEntitiesNetworkLocationsDetailsV1RequestMessage as Request45,
    GetEntitiesNetworkLocationsDetailsV1ResponseMessage as Response45,
    GetEntitiesNetworkLocationsV1RequestMessage as Request46,
    GetEntitiesNetworkLocationsV1ResponseMessage as Response46,
    GetEntitiesPlatformsV1RequestMessage as Request47,
    GetEntitiesPlatformsV1ResponseMessage as Response47,
    GetEntitiesPoliciesV1RequestMessage as Request48,
    GetEntitiesPoliciesV1ResponseMessage as Response48,
    GetEntitiesRuleGroupsV1RequestMessage as Request49,
    GetEntitiesRuleGroupsV1ResponseMessage as Response49,
    GetEntitiesRulesV1RequestMessage as Request410,
    GetEntitiesRulesV1ResponseMessage as Response410,
    GetLibraryEntitiesRuleGroupsV1RequestMessage as Request411,
    GetLibraryEntitiesRuleGroupsV1ResponseMessage as Response411,
    GetLibraryQueriesRuleGroupsV1RequestMessage as Request412,
    GetLibraryQueriesRuleGroupsV1ResponseMessage as Response412,
    GetQueriesEventsV1RequestMessage as Request413,
    GetQueriesEventsV1ResponseMessage as Response413,
    GetQueriesFirewallFieldsV1RequestMessage as Request414,
    GetQueriesFirewallFieldsV1ResponseMessage as Response414,
    GetQueriesNetworkLocationsV1RequestMessage as Request415,
    GetQueriesNetworkLocationsV1ResponseMessage as Response415,
    GetQueriesPlatformsV1RequestMessage as Request416,
    GetQueriesPlatformsV1ResponseMessage as Response416,
    GetQueriesPolicyRulesV1RequestMessage as Request417,
    GetQueriesPolicyRulesV1ResponseMessage as Response417,
    GetQueriesRuleGroupsV1RequestMessage as Request418,
    GetQueriesRuleGroupsV1ResponseMessage as Response418,
    GetQueriesRulesV1RequestMessage as Request419,
    GetQueriesRulesV1ResponseMessage as Response419,
    PatchEntitiesNetworkLocationsV1RequestMessage as Request420,
    PatchEntitiesNetworkLocationsV1ResponseMessage as Response420,
    PatchEntitiesRuleGroupsV1RequestMessage as Request421,
    PatchEntitiesRuleGroupsV1ResponseMessage as Response421,
    PostAggregatesEventsGetV1RequestMessage as Request422,
    PostAggregatesEventsGetV1ResponseMessage as Response422,
    PostAggregatesPolicyRulesGetV1RequestMessage as Request423,
    PostAggregatesPolicyRulesGetV1ResponseMessage as Response423,
    PostAggregatesRuleGroupsGetV1RequestMessage as Request424,
    PostAggregatesRuleGroupsGetV1ResponseMessage as Response424,
    PostAggregatesRulesGetV1RequestMessage as Request425,
    PostAggregatesRulesGetV1ResponseMessage as Response425,
    PostEntitiesNetworkLocationsMetadataV1RequestMessage as Request426,
    PostEntitiesNetworkLocationsMetadataV1ResponseMessage as Response426,
    PostEntitiesNetworkLocationsPrecedenceV1RequestMessage as Request427,
    PostEntitiesNetworkLocationsPrecedenceV1ResponseMessage as Response427,
    PostEntitiesNetworkLocationsV1RequestMessage as Request428,
    PostEntitiesNetworkLocationsV1ResponseMessage as Response428,
    PostEntitiesOntologyV1RequestMessage as Request429,
    PostEntitiesOntologyV1ResponseMessage as Response429,
    PostEntitiesRuleGroupsV1RequestMessage as Request430,
    PostEntitiesRuleGroupsV1ResponseMessage as Response430,
    PostEntitiesRulesValidateFilepathV1RequestMessage as Request431,
    PostEntitiesRulesValidateFilepathV1ResponseMessage as Response431,
    PutEntitiesNetworkLocationsV1RequestMessage as Request432,
    PutEntitiesNetworkLocationsV1ResponseMessage as Response432,
    PutEntitiesPoliciesV2RequestMessage as Request433,
    PutEntitiesPoliciesV2ResponseMessage as Response433,
    } from './fwmgr/types';

    import {
    
    GetCombinedCrowdscoresV1RequestMessage as Request50,
    GetCombinedCrowdscoresV1ResponseMessage as Response50,
    GetQueriesBehaviorsV1RequestMessage as Request51,
    GetQueriesBehaviorsV1ResponseMessage as Response51,
    GetQueriesIncidentsV1RequestMessage as Request52,
    GetQueriesIncidentsV1ResponseMessage as Response52,
    PostAggregatesBehaviorsGetV1RequestMessage as Request53,
    PostAggregatesBehaviorsGetV1ResponseMessage as Response53,
    PostAggregatesIncidentsGetV1RequestMessage as Request54,
    PostAggregatesIncidentsGetV1ResponseMessage as Response54,
    PostEntitiesBehaviorsGetV1RequestMessage as Request55,
    PostEntitiesBehaviorsGetV1ResponseMessage as Response55,
    PostEntitiesIncidentActionsV1RequestMessage as Request56,
    PostEntitiesIncidentActionsV1ResponseMessage as Response56,
    PostEntitiesIncidentsGetV1RequestMessage as Request57,
    PostEntitiesIncidentsGetV1ResponseMessage as Response57,
    } from './incidents/types';

    import {
    
    GetQueriesScriptsV1RequestMessage as Request60,
    GetQueriesScriptsV1ResponseMessage as Response60,
    PostEntitiesScriptsGetV2RequestMessage as Request61,
    PostEntitiesScriptsGetV2ResponseMessage as Response61,
    } from './remote-response/types';

    import {
    
    GetEntitiesExecutionResultsV1RequestMessage as Request70,
    GetEntitiesExecutionResultsV1ResponseMessage as Response70,
    PostEntitiesExecuteV1RequestMessage as Request71,
    PostEntitiesExecuteV1ResponseMessage as Response71,
    PostEntitiesExecutionActionsV1RequestMessage as Request72,
    PostEntitiesExecutionActionsV1ResponseMessage as Response72,
    } from './workflows/types';


// @todo can we make this less explicit?
export type ResponseFor<
  REQ extends RequestMessage,
  DATA extends LocalData
> = REQ extends ConnectRequestMessage
  ? ConnectResponseMessage<DATA>
    
        : REQ extends Request00
        ? Response00
        : REQ extends Request01
        ? Response01
        : REQ extends Request02
        ? Response02
        : REQ extends Request03
        ? Response03
        : REQ extends Request04
        ? Response04
        : REQ extends Request10
        ? Response10
        : REQ extends Request11
        ? Response11
        : REQ extends Request12
        ? Response12
        : REQ extends Request13
        ? Response13
        : REQ extends Request14
        ? Response14
        : REQ extends Request15
        ? Response15
        : REQ extends Request16
        ? Response16
        : REQ extends Request17
        ? Response17
        : REQ extends Request20
        ? Response20
        : REQ extends Request21
        ? Response21
        : REQ extends Request22
        ? Response22
        : REQ extends Request23
        ? Response23
        : REQ extends Request24
        ? Response24
        : REQ extends Request25
        ? Response25
        : REQ extends Request26
        ? Response26
        : REQ extends Request30
        ? Response30
        : REQ extends Request31
        ? Response31
        : REQ extends Request32
        ? Response32
        : REQ extends Request33
        ? Response33
        : REQ extends Request34
        ? Response34
        : REQ extends Request35
        ? Response35
        : REQ extends Request36
        ? Response36
        : REQ extends Request37
        ? Response37
        : REQ extends Request38
        ? Response38
        : REQ extends Request39
        ? Response39
        : REQ extends Request310
        ? Response310
        : REQ extends Request311
        ? Response311
        : REQ extends Request312
        ? Response312
        : REQ extends Request313
        ? Response313
        : REQ extends Request314
        ? Response314
        : REQ extends Request315
        ? Response315
        : REQ extends Request316
        ? Response316
        : REQ extends Request317
        ? Response317
        : REQ extends Request318
        ? Response318
        : REQ extends Request319
        ? Response319
        : REQ extends Request320
        ? Response320
        : REQ extends Request40
        ? Response40
        : REQ extends Request41
        ? Response41
        : REQ extends Request42
        ? Response42
        : REQ extends Request43
        ? Response43
        : REQ extends Request44
        ? Response44
        : REQ extends Request45
        ? Response45
        : REQ extends Request46
        ? Response46
        : REQ extends Request47
        ? Response47
        : REQ extends Request48
        ? Response48
        : REQ extends Request49
        ? Response49
        : REQ extends Request410
        ? Response410
        : REQ extends Request411
        ? Response411
        : REQ extends Request412
        ? Response412
        : REQ extends Request413
        ? Response413
        : REQ extends Request414
        ? Response414
        : REQ extends Request415
        ? Response415
        : REQ extends Request416
        ? Response416
        : REQ extends Request417
        ? Response417
        : REQ extends Request418
        ? Response418
        : REQ extends Request419
        ? Response419
        : REQ extends Request420
        ? Response420
        : REQ extends Request421
        ? Response421
        : REQ extends Request422
        ? Response422
        : REQ extends Request423
        ? Response423
        : REQ extends Request424
        ? Response424
        : REQ extends Request425
        ? Response425
        : REQ extends Request426
        ? Response426
        : REQ extends Request427
        ? Response427
        : REQ extends Request428
        ? Response428
        : REQ extends Request429
        ? Response429
        : REQ extends Request430
        ? Response430
        : REQ extends Request431
        ? Response431
        : REQ extends Request432
        ? Response432
        : REQ extends Request433
        ? Response433
        : REQ extends Request50
        ? Response50
        : REQ extends Request51
        ? Response51
        : REQ extends Request52
        ? Response52
        : REQ extends Request53
        ? Response53
        : REQ extends Request54
        ? Response54
        : REQ extends Request55
        ? Response55
        : REQ extends Request56
        ? Response56
        : REQ extends Request57
        ? Response57
        : REQ extends Request60
        ? Response60
        : REQ extends Request61
        ? Response61
        : REQ extends Request70
        ? Response70
        : REQ extends Request71
        ? Response71
        : REQ extends Request72
        ? Response72: unknown;
