/**
 *
 * This file is autogenerated.
 *
 * DO NOT EDIT DIRECTLY
 *
 **/

import { ActorsApiRequestMessage, ActorsApiResponseMessage } from './actors';
import { AlertsApiRequestMessage, AlertsApiResponseMessage } from './alerts';
import {
  CustomobjectsApiRequestMessage,
  CustomobjectsApiResponseMessage,
} from './customobjects';
import { DetectsApiRequestMessage, DetectsApiResponseMessage } from './detects';
import { DevicesApiRequestMessage, DevicesApiResponseMessage } from './devices';
import {
  FaasGatewayApiRequestMessage,
  FaasGatewayApiResponseMessage,
} from './faas-gateway';
import { FwmgrApiRequestMessage, FwmgrApiResponseMessage } from './fwmgr';
import {
  IncidentsApiRequestMessage,
  IncidentsApiResponseMessage,
} from './incidents';
import {
  LoggingapiApiRequestMessage,
  LoggingapiApiResponseMessage,
} from './loggingapi';
import { MitreApiRequestMessage, MitreApiResponseMessage } from './mitre';
import { PluginsApiRequestMessage, PluginsApiResponseMessage } from './plugins';
import {
  RemoteResponseApiRequestMessage,
  RemoteResponseApiResponseMessage,
} from './remote-response';
import {
  UserManagementApiRequestMessage,
  UserManagementApiResponseMessage,
} from './user-management';
import {
  WorkflowsApiRequestMessage,
  WorkflowsApiResponseMessage,
} from './workflows';

export {
  ActorsApiRequestMessage,
  ActorsApiResponseMessage,
  AlertsApiRequestMessage,
  AlertsApiResponseMessage,
  DetectsApiRequestMessage,
  DetectsApiResponseMessage,
  DevicesApiRequestMessage,
  DevicesApiResponseMessage,
  FwmgrApiRequestMessage,
  FwmgrApiResponseMessage,
  IncidentsApiRequestMessage,
  IncidentsApiResponseMessage,
  MitreApiRequestMessage,
  MitreApiResponseMessage,
  PluginsApiRequestMessage,
  PluginsApiResponseMessage,
  RemoteResponseApiRequestMessage,
  RemoteResponseApiResponseMessage,
  UserManagementApiRequestMessage,
  UserManagementApiResponseMessage,
  WorkflowsApiRequestMessage,
  WorkflowsApiResponseMessage,
  CustomobjectsApiRequestMessage,
  CustomobjectsApiResponseMessage,
  FaasGatewayApiRequestMessage,
  FaasGatewayApiResponseMessage,
  LoggingapiApiRequestMessage,
  LoggingapiApiResponseMessage,
};

export type ApiRequestMessage =
  | ActorsApiRequestMessage
  | AlertsApiRequestMessage
  | DetectsApiRequestMessage
  | DevicesApiRequestMessage
  | FwmgrApiRequestMessage
  | IncidentsApiRequestMessage
  | MitreApiRequestMessage
  | PluginsApiRequestMessage
  | RemoteResponseApiRequestMessage
  | UserManagementApiRequestMessage
  | WorkflowsApiRequestMessage
  | CustomobjectsApiRequestMessage
  | FaasGatewayApiRequestMessage
  | LoggingapiApiRequestMessage;

export type ApiResponseMessage =
  | ActorsApiResponseMessage
  | AlertsApiResponseMessage
  | DetectsApiResponseMessage
  | DevicesApiResponseMessage
  | FwmgrApiResponseMessage
  | IncidentsApiResponseMessage
  | MitreApiResponseMessage
  | PluginsApiResponseMessage
  | RemoteResponseApiResponseMessage
  | UserManagementApiResponseMessage
  | WorkflowsApiResponseMessage
  | CustomobjectsApiResponseMessage
  | FaasGatewayApiResponseMessage
  | LoggingapiApiResponseMessage;
