/**
 *
 * This file is autogenerated from the available APIs for App Platform.
 *
 * DO NOT EDIT DIRECTLY
 *
 * If you need to change the contents of this file please edit the above configuration file and
 * then run:
 *
 * ```
 * yarn cs-gen platform-apis
 * ```
 *
 **/

import { ActorsApiRequestMessage, ActorsApiResponseMessage } from './actors';
import { AlertsApiRequestMessage, AlertsApiResponseMessage } from './alerts';
import { CustomobjectsApiRequestMessage, CustomobjectsApiResponseMessage } from './customobjects';
import { DetectsApiRequestMessage, DetectsApiResponseMessage } from './detects';
import { DevicesApiRequestMessage, DevicesApiResponseMessage } from './devices';
import { FaasGatewayApiRequestMessage, FaasGatewayApiResponseMessage } from './faas-gateway';
import { FwmgrApiRequestMessage, FwmgrApiResponseMessage } from './fwmgr';
import { IncidentsApiRequestMessage, IncidentsApiResponseMessage } from './incidents';
import { LoggingapiApiRequestMessage, LoggingapiApiResponseMessage } from './loggingapi';
import { MitreApiRequestMessage, MitreApiResponseMessage } from './mitre';
import { PluginsApiRequestMessage, PluginsApiResponseMessage } from './plugins';
import {
  RemoteResponseApiRequestMessage,
  RemoteResponseApiResponseMessage,
} from './remote-response';
import { WorkflowsApiRequestMessage, WorkflowsApiResponseMessage } from './workflows';

export {
  ActorsApiRequestMessage,
  ActorsApiResponseMessage,
  AlertsApiRequestMessage,
  AlertsApiResponseMessage,
  DetectsApiRequestMessage,
  DetectsApiResponseMessage,
  DevicesApiRequestMessage,
  DevicesApiResponseMessage,
  FwmgrApiRequestMessage,
  FwmgrApiResponseMessage,
  IncidentsApiRequestMessage,
  IncidentsApiResponseMessage,
  MitreApiRequestMessage,
  MitreApiResponseMessage,
  PluginsApiRequestMessage,
  PluginsApiResponseMessage,
  RemoteResponseApiRequestMessage,
  RemoteResponseApiResponseMessage,
  WorkflowsApiRequestMessage,
  WorkflowsApiResponseMessage,
  CustomobjectsApiRequestMessage,
  CustomobjectsApiResponseMessage,
  FaasGatewayApiRequestMessage,
  FaasGatewayApiResponseMessage,
  LoggingapiApiRequestMessage,
  LoggingapiApiResponseMessage,
};

export type ApiRequestMessage =
  | ActorsApiRequestMessage
  | AlertsApiRequestMessage
  | DetectsApiRequestMessage
  | DevicesApiRequestMessage
  | FwmgrApiRequestMessage
  | IncidentsApiRequestMessage
  | MitreApiRequestMessage
  | PluginsApiRequestMessage
  | RemoteResponseApiRequestMessage
  | WorkflowsApiRequestMessage
  | CustomobjectsApiRequestMessage
  | FaasGatewayApiRequestMessage
  | LoggingapiApiRequestMessage;

export type ApiResponseMessage =
  | ActorsApiResponseMessage
  | AlertsApiResponseMessage
  | DetectsApiResponseMessage
  | DevicesApiResponseMessage
  | FwmgrApiResponseMessage
  | IncidentsApiResponseMessage
  | MitreApiResponseMessage
  | PluginsApiResponseMessage
  | RemoteResponseApiResponseMessage
  | WorkflowsApiResponseMessage
  | CustomobjectsApiResponseMessage
  | FaasGatewayApiResponseMessage
  | LoggingapiApiResponseMessage;
