/**
 *
 * This file is autogenerated from the available APIs for App Platform.
 *
 * DO NOT EDIT DIRECTLY
 *
 * If you need to change the contents of this file please edit the above configuration file and
 * then run:
 *
 * ```
 * yarn cs-gen platform-apis
 * ```
 *
 **/

import {
  ConnectRequestMessage,
  LocalData,
  ConnectResponseMessage,
  DataUpdateMessage
} from '../types';


import { ActorsApiRequestMessage, ActorsApiResponseMessage } from './actors/types';
import { AlertsApiRequestMessage, AlertsApiResponseMessage } from './alerts/types';
import { DetectsApiRequestMessage, DetectsApiResponseMessage } from './detects/types';
import { DevicesApiRequestMessage, DevicesApiResponseMessage } from './devices/types';
import { FwmgrApiRequestMessage, FwmgrApiResponseMessage } from './fwmgr/types';
import { IncidentsApiRequestMessage, IncidentsApiResponseMessage } from './incidents/types';
import { RemoteResponseApiRequestMessage, RemoteResponseApiResponseMessage } from './remote-response/types';
import { WorkflowsApiRequestMessage, WorkflowsApiResponseMessage } from './workflows/types';


export {

  ActorsApiRequestMessage,
  ActorsApiResponseMessage,
  AlertsApiRequestMessage,
  AlertsApiResponseMessage,
  DetectsApiRequestMessage,
  DetectsApiResponseMessage,
  DevicesApiRequestMessage,
  DevicesApiResponseMessage,
  FwmgrApiRequestMessage,
  FwmgrApiResponseMessage,
  IncidentsApiRequestMessage,
  IncidentsApiResponseMessage,
  RemoteResponseApiRequestMessage,
  RemoteResponseApiResponseMessage,
  WorkflowsApiRequestMessage,
  WorkflowsApiResponseMessage,
};

export type ApiRequestMessage = 
    | ActorsApiRequestMessage
    | AlertsApiRequestMessage
    | DetectsApiRequestMessage
    | DevicesApiRequestMessage
    | FwmgrApiRequestMessage
    | IncidentsApiRequestMessage
    | RemoteResponseApiRequestMessage
    | WorkflowsApiRequestMessage;

export type RequestMessage = ConnectRequestMessage | ApiRequestMessage;

export type ApiResponseMessage = 
  | ActorsApiResponseMessage
  | AlertsApiResponseMessage
  | DetectsApiResponseMessage
  | DevicesApiResponseMessage
  | FwmgrApiResponseMessage
  | IncidentsApiResponseMessage
  | RemoteResponseApiResponseMessage
  | WorkflowsApiResponseMessage;

export type ResponseMessage<DATA extends LocalData = LocalData> =
  | ConnectResponseMessage<DATA>
  | ApiResponseMessage
  | DataUpdateMessage<DATA>;

export type PayloadOf<RESPONSE extends ResponseMessage> = RESPONSE['payload'];