/**
 *
 * This file is autogenerated.
 *
 * DO NOT EDIT DIRECTLY
 *
 **/

import type { RequestMessage } from '../types';

import type {
  GetEntitiesActorsGetV2RequestMessage as Request00,
  GetQueriesActorsV2RequestMessage as Request01,
  PostAggregatesActorsGetV2RequestMessage as Request02,
  PostEntitiesActorsGetV2RequestMessage as Request03,
  PostEntitiesMitreV1RequestMessage as Request04,
  GetEntitiesActorsGetV2ResponseMessage as Response00,
  GetQueriesActorsV2ResponseMessage as Response01,
  PostAggregatesActorsGetV2ResponseMessage as Response02,
  PostEntitiesActorsGetV2ResponseMessage as Response03,
  PostEntitiesMitreV1ResponseMessage as Response04,
} from './actors';

import type {
  DeleteEntitiesSuppressedDevicesV1RequestMessage as Request10,
  GetQueriesAlertsV1RequestMessage as Request11,
  PatchCombinedAlertsV2RequestMessage as Request12,
  PatchEntitiesAlertsV2RequestMessage as Request13,
  PatchEntitiesSuppressedDevicesV1RequestMessage as Request14,
  PostAggregatesAlertsV1RequestMessage as Request15,
  PostEntitiesAlertsV1RequestMessage as Request16,
  PostEntitiesSuppressedDevicesV1RequestMessage as Request17,
  DeleteEntitiesSuppressedDevicesV1ResponseMessage as Response10,
  GetQueriesAlertsV1ResponseMessage as Response11,
  PatchCombinedAlertsV2ResponseMessage as Response12,
  PatchEntitiesAlertsV2ResponseMessage as Response13,
  PatchEntitiesSuppressedDevicesV1ResponseMessage as Response14,
  PostAggregatesAlertsV1ResponseMessage as Response15,
  PostEntitiesAlertsV1ResponseMessage as Response16,
  PostEntitiesSuppressedDevicesV1ResponseMessage as Response17,
} from './alerts';

import type {
  GetEntitiesSuppressedDevicesV1RequestMessage as Request20,
  PatchEntitiesDetectsV2RequestMessage as Request21,
  PatchQueriesDetectsV1RequestMessage as Request22,
  PatchQueriesDetectsV2RequestMessage as Request23,
  PostAggregatesDetectsGetV1RequestMessage as Request24,
  PostEntitiesSummariesGetV1RequestMessage as Request25,
  PostEntitiesSuppressedDevicesV1RequestMessage as Request26,
  GetEntitiesSuppressedDevicesV1ResponseMessage as Response20,
  PatchEntitiesDetectsV2ResponseMessage as Response21,
  PatchQueriesDetectsV1ResponseMessage as Response22,
  PatchQueriesDetectsV2ResponseMessage as Response23,
  PostAggregatesDetectsGetV1ResponseMessage as Response24,
  PostEntitiesSummariesGetV1ResponseMessage as Response25,
  PostEntitiesSuppressedDevicesV1ResponseMessage as Response26,
} from './detects';

import type {
  DeleteEntitiesGroupsV1RequestMessage as Request30,
  GetAggregatesBucketsV1RequestMessage as Request31,
  PatchEntitiesDevicesTagsV2RequestMessage as Request310,
  PatchEntitiesGroupsV1RequestMessage as Request311,
  PostAggregatesDevicesGetV1RequestMessage as Request312,
  PostCombinedDevicesLoginHistoryV1RequestMessage as Request313,
  PostEntitiesDevicesActionsV4RequestMessage as Request314,
  PostEntitiesDevicesHiddenActionsV4RequestMessage as Request315,
  PostEntitiesDevicesReportsV1RequestMessage as Request316,
  PostEntitiesDevicesV2RequestMessage as Request317,
  PostEntitiesGroupActionsV1RequestMessage as Request318,
  PostEntitiesGroupsV1RequestMessage as Request319,
  GetAggregatesTagPrefixCountsV1RequestMessage as Request32,
  PostEntitiesReleasesV1RequestMessage as Request320,
  GetEntitiesGroupsV1RequestMessage as Request33,
  GetEntitiesReleasesV1RequestMessage as Request34,
  GetEntitiesRespondV1RequestMessage as Request35,
  GetQueriesAvailableGroupsV1RequestMessage as Request36,
  GetQueriesDevicesHiddenV2RequestMessage as Request37,
  GetQueriesDevicesV2RequestMessage as Request38,
  GetQueriesGroupsV1RequestMessage as Request39,
  DeleteEntitiesGroupsV1ResponseMessage as Response30,
  GetAggregatesBucketsV1ResponseMessage as Response31,
  PatchEntitiesDevicesTagsV2ResponseMessage as Response310,
  PatchEntitiesGroupsV1ResponseMessage as Response311,
  PostAggregatesDevicesGetV1ResponseMessage as Response312,
  PostCombinedDevicesLoginHistoryV1ResponseMessage as Response313,
  PostEntitiesDevicesActionsV4ResponseMessage as Response314,
  PostEntitiesDevicesHiddenActionsV4ResponseMessage as Response315,
  PostEntitiesDevicesReportsV1ResponseMessage as Response316,
  PostEntitiesDevicesV2ResponseMessage as Response317,
  PostEntitiesGroupActionsV1ResponseMessage as Response318,
  PostEntitiesGroupsV1ResponseMessage as Response319,
  GetAggregatesTagPrefixCountsV1ResponseMessage as Response32,
  PostEntitiesReleasesV1ResponseMessage as Response320,
  GetEntitiesGroupsV1ResponseMessage as Response33,
  GetEntitiesReleasesV1ResponseMessage as Response34,
  GetEntitiesRespondV1ResponseMessage as Response35,
  GetQueriesAvailableGroupsV1ResponseMessage as Response36,
  GetQueriesDevicesHiddenV2ResponseMessage as Response37,
  GetQueriesDevicesV2ResponseMessage as Response38,
  GetQueriesGroupsV1ResponseMessage as Response39,
} from './devices';

import type {
  DeleteEntitiesNetworkLocationsV1RequestMessage as Request40,
  DeleteEntitiesPoliciesV1RequestMessage as Request41,
  GetEntitiesRulesV1RequestMessage as Request410,
  GetLibraryEntitiesRuleGroupsV1RequestMessage as Request411,
  GetLibraryQueriesRuleGroupsV1RequestMessage as Request412,
  GetQueriesEventsV1RequestMessage as Request413,
  GetQueriesFirewallFieldsV1RequestMessage as Request414,
  GetQueriesNetworkLocationsV1RequestMessage as Request415,
  GetQueriesPlatformsV1RequestMessage as Request416,
  GetQueriesPolicyRulesV1RequestMessage as Request417,
  GetQueriesRuleGroupsV1RequestMessage as Request418,
  GetQueriesRulesV1RequestMessage as Request419,
  DeleteEntitiesRuleGroupsV1RequestMessage as Request42,
  PatchEntitiesNetworkLocationsV1RequestMessage as Request420,
  PatchEntitiesRuleGroupsV1RequestMessage as Request421,
  PostAggregatesEventsGetV1RequestMessage as Request422,
  PostAggregatesPolicyRulesGetV1RequestMessage as Request423,
  PostAggregatesRuleGroupsGetV1RequestMessage as Request424,
  PostAggregatesRulesGetV1RequestMessage as Request425,
  PostEntitiesNetworkLocationsMetadataV1RequestMessage as Request426,
  PostEntitiesNetworkLocationsPrecedenceV1RequestMessage as Request427,
  PostEntitiesNetworkLocationsV1RequestMessage as Request428,
  PostEntitiesOntologyV1RequestMessage as Request429,
  GetEntitiesEventsV1RequestMessage as Request43,
  PostEntitiesRuleGroupsV1RequestMessage as Request430,
  PostEntitiesRulesValidateFilepathV1RequestMessage as Request431,
  PutEntitiesNetworkLocationsV1RequestMessage as Request432,
  PutEntitiesPoliciesV2RequestMessage as Request433,
  GetEntitiesFirewallFieldsV1RequestMessage as Request44,
  GetEntitiesNetworkLocationsDetailsV1RequestMessage as Request45,
  GetEntitiesNetworkLocationsV1RequestMessage as Request46,
  GetEntitiesPlatformsV1RequestMessage as Request47,
  GetEntitiesPoliciesV1RequestMessage as Request48,
  GetEntitiesRuleGroupsV1RequestMessage as Request49,
  DeleteEntitiesNetworkLocationsV1ResponseMessage as Response40,
  DeleteEntitiesPoliciesV1ResponseMessage as Response41,
  GetEntitiesRulesV1ResponseMessage as Response410,
  GetLibraryEntitiesRuleGroupsV1ResponseMessage as Response411,
  GetLibraryQueriesRuleGroupsV1ResponseMessage as Response412,
  GetQueriesEventsV1ResponseMessage as Response413,
  GetQueriesFirewallFieldsV1ResponseMessage as Response414,
  GetQueriesNetworkLocationsV1ResponseMessage as Response415,
  GetQueriesPlatformsV1ResponseMessage as Response416,
  GetQueriesPolicyRulesV1ResponseMessage as Response417,
  GetQueriesRuleGroupsV1ResponseMessage as Response418,
  GetQueriesRulesV1ResponseMessage as Response419,
  DeleteEntitiesRuleGroupsV1ResponseMessage as Response42,
  PatchEntitiesNetworkLocationsV1ResponseMessage as Response420,
  PatchEntitiesRuleGroupsV1ResponseMessage as Response421,
  PostAggregatesEventsGetV1ResponseMessage as Response422,
  PostAggregatesPolicyRulesGetV1ResponseMessage as Response423,
  PostAggregatesRuleGroupsGetV1ResponseMessage as Response424,
  PostAggregatesRulesGetV1ResponseMessage as Response425,
  PostEntitiesNetworkLocationsMetadataV1ResponseMessage as Response426,
  PostEntitiesNetworkLocationsPrecedenceV1ResponseMessage as Response427,
  PostEntitiesNetworkLocationsV1ResponseMessage as Response428,
  PostEntitiesOntologyV1ResponseMessage as Response429,
  GetEntitiesEventsV1ResponseMessage as Response43,
  PostEntitiesRuleGroupsV1ResponseMessage as Response430,
  PostEntitiesRulesValidateFilepathV1ResponseMessage as Response431,
  PutEntitiesNetworkLocationsV1ResponseMessage as Response432,
  PutEntitiesPoliciesV2ResponseMessage as Response433,
  GetEntitiesFirewallFieldsV1ResponseMessage as Response44,
  GetEntitiesNetworkLocationsDetailsV1ResponseMessage as Response45,
  GetEntitiesNetworkLocationsV1ResponseMessage as Response46,
  GetEntitiesPlatformsV1ResponseMessage as Response47,
  GetEntitiesPoliciesV1ResponseMessage as Response48,
  GetEntitiesRuleGroupsV1ResponseMessage as Response49,
} from './fwmgr';

import type {
  GetCombinedCrowdscoresV1RequestMessage as Request50,
  GetQueriesBehaviorsV1RequestMessage as Request51,
  GetQueriesIncidentsV1RequestMessage as Request52,
  PostAggregatesBehaviorsGetV1RequestMessage as Request53,
  PostAggregatesIncidentsGetV1RequestMessage as Request54,
  PostEntitiesBehaviorsGetV1RequestMessage as Request55,
  PostEntitiesIncidentActionsV1RequestMessage as Request56,
  PostEntitiesIncidentsGetV1RequestMessage as Request57,
  GetCombinedCrowdscoresV1ResponseMessage as Response50,
  GetQueriesBehaviorsV1ResponseMessage as Response51,
  GetQueriesIncidentsV1ResponseMessage as Response52,
  PostAggregatesBehaviorsGetV1ResponseMessage as Response53,
  PostAggregatesIncidentsGetV1ResponseMessage as Response54,
  PostEntitiesBehaviorsGetV1ResponseMessage as Response55,
  PostEntitiesIncidentActionsV1ResponseMessage as Response56,
  PostEntitiesIncidentsGetV1ResponseMessage as Response57,
} from './incidents';

import type {
  GetEntitiesMatrixV1RequestMessage as Request60,
  GetEntitiesMatrixV1ResponseMessage as Response60,
} from './mitre';

import type {
  GetEntitiesConfigsV1RequestMessage as Request70,
  PostEntitiesExecuteDraftV1RequestMessage as Request71,
  PostEntitiesExecuteV1RequestMessage as Request72,
  GetEntitiesConfigsV1ResponseMessage as Response70,
  PostEntitiesExecuteDraftV1ResponseMessage as Response71,
  PostEntitiesExecuteV1ResponseMessage as Response72,
} from './plugins';

import type {
  GetEntitiesAppCommandV1RequestMessage as Request80,
  GetQueriesScriptsV1RequestMessage as Request81,
  PostEntitiesAppCommandV1RequestMessage as Request82,
  PostEntitiesAppRefreshSessionsV1RequestMessage as Request83,
  PostEntitiesAppSessionsV1RequestMessage as Request84,
  PostEntitiesScriptsGetV2RequestMessage as Request85,
  GetEntitiesAppCommandV1ResponseMessage as Response80,
  GetQueriesScriptsV1ResponseMessage as Response81,
  PostEntitiesAppCommandV1ResponseMessage as Response82,
  PostEntitiesAppRefreshSessionsV1ResponseMessage as Response83,
  PostEntitiesAppSessionsV1ResponseMessage as Response84,
  PostEntitiesScriptsGetV2ResponseMessage as Response85,
} from './remote-response';

import type {
  GetQueriesUsersV1RequestMessage as Request90,
  PostEntitiesUsersGetV1RequestMessage as Request91,
  GetQueriesUsersV1ResponseMessage as Response90,
  PostEntitiesUsersGetV1ResponseMessage as Response91,
} from './user-management';

import type {
  GetEntitiesExecutionResultsV1RequestMessage as Request100,
  PostEntitiesExecuteV1RequestMessage as Request101,
  PostEntitiesExecutionActionsV1RequestMessage as Request102,
  GetEntitiesExecutionResultsV1ResponseMessage as Response100,
  PostEntitiesExecuteV1ResponseMessage as Response101,
  PostEntitiesExecutionActionsV1ResponseMessage as Response102,
} from './workflows';

import type {
  DeleteV1CollectionsCollectionNameObjectsObjectKeyRequestMessage as Request110,
  GetV1CollectionsRequestMessage as Request111,
  GetV1CollectionsCollectionNameObjectsRequestMessage as Request112,
  GetV1CollectionsCollectionNameObjectsObjectKeyRequestMessage as Request113,
  GetV1CollectionsCollectionNameObjectsObjectKeyMetadataRequestMessage as Request114,
  PostV1CollectionsCollectionNameObjectsRequestMessage as Request115,
  PutV1CollectionsCollectionNameObjectsObjectKeyRequestMessage as Request116,
  DeleteV1CollectionsCollectionNameObjectsObjectKeyResponseMessage as Response110,
  GetV1CollectionsResponseMessage as Response111,
  GetV1CollectionsCollectionNameObjectsResponseMessage as Response112,
  GetV1CollectionsCollectionNameObjectsObjectKeyResponseMessage as Response113,
  GetV1CollectionsCollectionNameObjectsObjectKeyMetadataResponseMessage as Response114,
  PostV1CollectionsCollectionNameObjectsResponseMessage as Response115,
  PutV1CollectionsCollectionNameObjectsObjectKeyResponseMessage as Response116,
} from './customobjects';

import type {
  GetEntitiesExecutionV1RequestMessage as Request120,
  PostEntitiesExecutionV1RequestMessage as Request121,
  GetEntitiesExecutionV1ResponseMessage as Response120,
  PostEntitiesExecutionV1ResponseMessage as Response121,
} from './faas-gateway';

import type {
  GetEntitiesSavedSearchesExecuteV1RequestMessage as Request130,
  PostEntitiesSavedSearchesExecuteV1RequestMessage as Request131,
  GetEntitiesSavedSearchesExecuteV1ResponseMessage as Response130,
  PostEntitiesSavedSearchesExecuteV1ResponseMessage as Response131,
} from './loggingapi';

export type ResponseFor<REQ extends RequestMessage> = REQ extends Request00
  ? Response00
  : REQ extends Request01
  ? Response01
  : REQ extends Request02
  ? Response02
  : REQ extends Request03
  ? Response03
  : REQ extends Request04
  ? Response04
  : REQ extends Request10
  ? Response10
  : REQ extends Request11
  ? Response11
  : REQ extends Request12
  ? Response12
  : REQ extends Request13
  ? Response13
  : REQ extends Request14
  ? Response14
  : REQ extends Request15
  ? Response15
  : REQ extends Request16
  ? Response16
  : REQ extends Request17
  ? Response17
  : REQ extends Request20
  ? Response20
  : REQ extends Request21
  ? Response21
  : REQ extends Request22
  ? Response22
  : REQ extends Request23
  ? Response23
  : REQ extends Request24
  ? Response24
  : REQ extends Request25
  ? Response25
  : REQ extends Request26
  ? Response26
  : REQ extends Request30
  ? Response30
  : REQ extends Request31
  ? Response31
  : REQ extends Request32
  ? Response32
  : REQ extends Request33
  ? Response33
  : REQ extends Request34
  ? Response34
  : REQ extends Request35
  ? Response35
  : REQ extends Request36
  ? Response36
  : REQ extends Request37
  ? Response37
  : REQ extends Request38
  ? Response38
  : REQ extends Request39
  ? Response39
  : REQ extends Request310
  ? Response310
  : REQ extends Request311
  ? Response311
  : REQ extends Request312
  ? Response312
  : REQ extends Request313
  ? Response313
  : REQ extends Request314
  ? Response314
  : REQ extends Request315
  ? Response315
  : REQ extends Request316
  ? Response316
  : REQ extends Request317
  ? Response317
  : REQ extends Request318
  ? Response318
  : REQ extends Request319
  ? Response319
  : REQ extends Request320
  ? Response320
  : REQ extends Request40
  ? Response40
  : REQ extends Request41
  ? Response41
  : REQ extends Request42
  ? Response42
  : REQ extends Request43
  ? Response43
  : REQ extends Request44
  ? Response44
  : REQ extends Request45
  ? Response45
  : REQ extends Request46
  ? Response46
  : REQ extends Request47
  ? Response47
  : REQ extends Request48
  ? Response48
  : REQ extends Request49
  ? Response49
  : REQ extends Request410
  ? Response410
  : REQ extends Request411
  ? Response411
  : REQ extends Request412
  ? Response412
  : REQ extends Request413
  ? Response413
  : REQ extends Request414
  ? Response414
  : REQ extends Request415
  ? Response415
  : REQ extends Request416
  ? Response416
  : REQ extends Request417
  ? Response417
  : REQ extends Request418
  ? Response418
  : REQ extends Request419
  ? Response419
  : REQ extends Request420
  ? Response420
  : REQ extends Request421
  ? Response421
  : REQ extends Request422
  ? Response422
  : REQ extends Request423
  ? Response423
  : REQ extends Request424
  ? Response424
  : REQ extends Request425
  ? Response425
  : REQ extends Request426
  ? Response426
  : REQ extends Request427
  ? Response427
  : REQ extends Request428
  ? Response428
  : REQ extends Request429
  ? Response429
  : REQ extends Request430
  ? Response430
  : REQ extends Request431
  ? Response431
  : REQ extends Request432
  ? Response432
  : REQ extends Request433
  ? Response433
  : REQ extends Request50
  ? Response50
  : REQ extends Request51
  ? Response51
  : REQ extends Request52
  ? Response52
  : REQ extends Request53
  ? Response53
  : REQ extends Request54
  ? Response54
  : REQ extends Request55
  ? Response55
  : REQ extends Request56
  ? Response56
  : REQ extends Request57
  ? Response57
  : REQ extends Request60
  ? Response60
  : REQ extends Request70
  ? Response70
  : REQ extends Request71
  ? Response71
  : REQ extends Request72
  ? Response72
  : REQ extends Request80
  ? Response80
  : REQ extends Request81
  ? Response81
  : REQ extends Request82
  ? Response82
  : REQ extends Request83
  ? Response83
  : REQ extends Request84
  ? Response84
  : REQ extends Request85
  ? Response85
  : REQ extends Request90
  ? Response90
  : REQ extends Request91
  ? Response91
  : REQ extends Request100
  ? Response100
  : REQ extends Request101
  ? Response101
  : REQ extends Request102
  ? Response102
  : REQ extends Request110
  ? Response110
  : REQ extends Request111
  ? Response111
  : REQ extends Request112
  ? Response112
  : REQ extends Request113
  ? Response113
  : REQ extends Request114
  ? Response114
  : REQ extends Request115
  ? Response115
  : REQ extends Request116
  ? Response116
  : REQ extends Request120
  ? Response120
  : REQ extends Request121
  ? Response121
  : REQ extends Request130
  ? Response130
  : REQ extends Request131
  ? Response131
  : unknown;
