/**
 *
 * This file is autogenerated from the configuration file at `config/apis/incidents.json`.
 *
 * DO NOT EDIT DIRECTLY
 *
 * If you need to change the contents of this file please edit the above configuration file and
 * then run:
 *
 * ```
 * yarn cs-gen platform-apis
 * ```
 *
 **/

import { ApiRequestMessage } from '../../types';
import type { BaseUrlParams, QueryParam } from '../types';

export type IncidentsRequestApi = 'incidents';

export interface GetQueriesIncidentsV1QueryParams extends BaseUrlParams {
  filter?: string;
  limit?: QueryParam;
  offset?: QueryParam;
  sort?: QueryParam;
}

export interface PostEntitiesIncidentsGetV1QueryParams extends BaseUrlParams {}

export interface PostEntitiesIncidentsGetV1PostData {}

export type GetQueriesIncidentsV1ApiResponse = any;

export type PostEntitiesIncidentsGetV1ApiResponse = any;

export interface GetQueriesIncidentsV1RequestMessage extends ApiRequestMessage {
  api: IncidentsRequestApi;
  method: 'getQueriesIncidentsV1';
  payload: {
    params: GetQueriesIncidentsV1QueryParams;
  };
}

export interface PostEntitiesIncidentsGetV1RequestMessage
  extends ApiRequestMessage {
  api: IncidentsRequestApi;
  method: 'postEntitiesIncidentsGetV1';
  payload: {
    body: PostEntitiesIncidentsGetV1PostData;
    params: PostEntitiesIncidentsGetV1QueryParams;
  };
}
